apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  ingress.yaml: |
  envoy.yaml: |
    node:
      cluster: gateway
      id: master
    
    admin:
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 9901

    dynamic_resources:
      cds_config:
        path: /data/dynamic_resources/clusters.yaml
        resource_api_version: V3
      lds_config:
        path: /data/dynamic_resources/listeners.yaml
        resource_api_version: V3
  clusters.yaml: |
    resources:
      - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
        name: local_admin
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: local_admin
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: 127.0.0.1
                        port_value: 9901
  listeners.yaml: |
    resources:
      - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
        name: demo_ingress
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 80
        filter_chains:
          - filters:
              - name: envoy.http_connection_manager
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                  stat_prefix: demo_ingress
                  http_filters:
                    - name: envoy.filters.http.router
                  route_config:
                    name: local_route
                    virtual_hosts:
                      - name: "*"
                        domains:
                          - "*"
                        routes:
                          - match:
                              prefix: /ready
                            route:
                              cluster: local_admin
